### ISSUE TITLE
cannot work with @svgdotjs/svg.js@3.0.13

### ISSUE THREAD

**Issue by bossonchan** [svgdotjs/svg.filter.js#38]
This package has the dependency: @svgdotjs/svg.js@3.0.12

When upgrading @svgdotjs/svg.js from 3.0.12 to 3.0.13, it won't work

```
const svg = require("@svgdotjs/svg.js")
require("@svgdotjs/svg.filter.js")

const group = new svg.G()
console.log(group);
console.log(group.filter); // undefined
```

**Comment by PiotrFr** [comment]
`ERROR in node_modules/@svgdotjs/svg.filter.js/node_modules/@svgdotjs/svg.js/svg.js.d.ts(1,1): error TS6200: Definitions of the following identifiers conflict with those in another file: 
BuiltInArray, utils, defaults, easing, regex, namespaces, AttrNumberValue, SVGTypeMapping, SvgType, ClipPathType, TextType, GType, AType, ParentElement, AttrTypeMapping, ElementAlias, AttributeReference, ArrayAlias, Array, Point, PointArray, NumberUnit, Number, NumberAlias, LineCommand, CurveCommand, PathCommand, PathArrayAlias, PathArray, FlipType, ArrayXY, CoordinateXY, MatrixAlias, Matrix, ColorAlias, Color, Box, MorphValueLike, Morphable, ObjectBag, NonMorphable, TransformBag, Ease, Controller, Queue, Timeline, TimeLike, Runner, Animator, ParentTypnode_modules/@svgdotjs/svg.filter.js/node_modules/@svgdotjs/svg.js/svg.js.d.ts(1294,11): error TS2420: Class 'Circle' incorrectly implements interface 'CircleMethods'.  Type 'Circle' is missing the following properties from type 'CircleMethods': delay, filterWith, filterer, unfilter, draggable
node_modules/@svgdotjs/svg.filter.js/node_modules/@svgdotjs/svg.js/svg.js.d.ts(1305,11): error TS2420: Class 'Ellipse' incorrectly implements interface 'CircleMethods'.
  Type 'Ellipse' is missing the following properties from type 'CircleMethods': delay, filterWith, filterer, unfilter, draggable
node_modules/@svgdotjs/svg.js/svg.js.d.ts(5,1): error TS6200: Definitions of the following identifiers conflict with those in another file: BuiltInArray, utils, defaults, easing, regex, 
namespaces, AttrNumberValue, SVGTypeMapping, SvgType, ClipPathType, TextType, GType, AType, ParentElement, AttrTypeMapping, ElementAlias, AttributeReference, ArrayAlias, Array, Point, PointArray, NumberUnit, Number, NumberAlias, LineCommand, CurveCommand, PathCommand, PathArrayAlias, PathArray, FlipType, ArrayXY, CoordinateXY, MatrixAlias, Matrix, ColorAlias, Color, Box, MorphValueLike, Morphable, ObjectBag, NonMorphable, TransformBag, Ease, Controller, Queue, Timeline, TimeLike, Runner, Animator, ParentTypeAlias, QuerySelector, ParentQueryAlias, ParentQueryMapping, ParentQueryResultMapping, PutInMapping, PutInResultMapping, Dom, ClipPath, Container, Defs, Svg, Symbol, Element, Circle, Ellipse, Stop, Gradient, G, A, Image, PointArrayAlias, Line, Marker, Mask, Path, Pattern, Polyline, Polygon, Rect, Shape, Text, Tspan, TextPath, Use, ViewBoxAlias
node_modules/@svgdotjs/svg.js/svg.js.d.ts(1511,11): error TS2420: Class 'Polyline' incorrectly implements interface 'poly'.
  Property '_array' is missing in type 'Polyline' but required in type 'poly'.
node_modules/@svgdotjs/svg.js/svg.js.d.ts(1526,11): error TS2420: Class 'Polygon' incorrectly implements interface 'poly'.
  Property '_array' is missing in type 'Polygon' but required in type 'poly'.`
